name: GKE CI/CD

on:
  push:
    branches:
      - staging 
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID}}
  GKE_CLUSTER: gke-casan-cluster    # Add your cluster name here.
  GKE_ZONE: asia-southeast2-b   # Add your cluster zone here.
  REPOSITORY_NAME: casan-frontend
  REGION: asia-southeast2
  CLUSTER_NAME: gke-casan-cluster

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Google Cloud SDK
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_KEY_JSON}}

      # Step 3: Configure Docker to use GCP Artifact Registry
      - name: Configure Docker authentication
        run: gcloud --quiet auth configure-docker $REGION-docker.pkg.dev

      # 
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          project_id: ${{ env.PROJECT_ID }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
      - name: Docker login to Artifact Registry
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-southeast2-docker.pkg.dev


      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            IMAGE_TAG="stg-latest"
            NAMESPACE="staging"
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            IMAGE_TAG="prd-latest"
            NAMESPACE="production"
          fi
          IMAGE_NAME=$REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPOSITORY_NAME/casan-frontend:$IMAGE_TAG
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

          IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME)
          echo "IMAGE_SHA=$IMAGE_SHA" >> $GITHUB_ENV

      # Step 5: Deploy to GKE
      - name: Deploy to GKE
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            IMAGE_TAG="stg-latest"
            NAMESPACE="staging"
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            IMAGE_TAG="prd-latest"
            NAMESPACE="production"
          fi
          kubectl config use-context gke_${{ secrets.GCP_PROJECT_ID }}_$REGION-b_$CLUSTER_NAME
          kubectl set image deployment/casan-frontend casan-frontend=$IMAGE_SHA --namespace=$NAMESPACE
          kubectl rollout restart deployment/casan-frontend -n $NAMESPACE


